
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[31,)" #mandatory (28 is current forge version)
issueTrackerURL="https://github.com/mcenderdragon/DefaultDimension/issues"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="defaultdimension" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Default Dimension" #mandatory
updateJSONURL="http://myurl.me/" #optional
#displayURL="http://example.com/" #optional
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="MCenderdragon"
description='''
With this mod you can change the default spawn dimension of the player. Also a spread command across dimensions is added, checkout the configs for al options.
'''
[[dependencies.defaultdimension]] #optional
    modId="forge"
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.defaultdimension]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
